### ISSUE TITLE
1.12.1 Compatibility

### ISSUE THREAD

**Issue by KevinTyrrell** [Schaka/LoseControl#2]
Is this possible to be used on 1.12.1? If no, what changes need to be made?

**Comment by Schaka** [comment]
http://www.mediafire.com/download/1n9gsaof99mg370/LoseControl.zip
Take a look into the vanilla version of it. I didn't spend much time on it, so it's somewhat broken. But if you have any Lua knowledge and take a look at the this repo, you can figure it out.

Also taking a look at EnemyBuffTimersVanilla might help with the cooldown frame scaling.
