### ISSUE TITLE
Nil Value Bug - Please Help 

### ISSUE THREAD

**Issue by Medyzz** [Schaka/LoseControl#5]
Hi Schaka, apparently I only once changed in the LC settings to show roots on portraits and since then silences/CC was covered by Roots so I unticked "roots" in the menu but even reinstalling the addon or whatever doesnt help and I get this message all the time: 

Date: 2017-11-02 06:10:29
ID: 53
Error occured in: Global
Count: 1
Message: ..\AddOns\LoseControl\LoseControl.lua line 270:
   attempt to index upvalue 'LoseControlDB' (a nil value)
Debug:
   [C]: ?
   LoseControl\LoseControl.lua:270: ?()
   LoseControl\LoseControl.lua:226:
      LoseControl\LoseControl.lua:225
AddOns:
  Aloft, vr69448
  AtlasLoot, vAtlasLoot Enhanced v4.06.04
  AucAdvanced, v5.0.0
  AucFilterBasic, v5.0.0 (BillyGoat)
  AucStatClassic, v5.0.0 (BillyGoat)
  AucStatHistogram, v5.0.0 (BillyGoat)
  AucStatPurchased, v5.0.0 (BillyGoat)
  AucStatSimple, v5.0.0 (BillyGoat)
  AucStatStdDev, v5.0.0 (BillyGoat)
  Auctioneer, v5.0.0
  Bagnon, v1.5.2
  BagnonForever, v1.0.0
  BagnonTooltips
  BuffLib
  Capping, v2.4.011
  Cartographer, vr74405
  ClassColoredNameplates
  CombatLogFix
  Dominos, v1.3.3
  DominosBuff
  DominosCast
  DominosRoll
  DominosXP
  EnhTooltip, v5.0.0
  FocusFrame, v2.3.6
  Gladdy
  LoseControl, v3.31
  MobHealth, v3.3
  MobMap, vMobMap v2.12
  MoveAnything
  OmniCC, v2.5.9
  Postal, v2.1 r79759
  RatingBuster, v1.3.7 (r77560)
  SpeedyActions, v4
  Stubby, v93
  Swatter, v5.0.0
  Talented, v1.3
  XLoot, v0.9

Do you know how to fix this please? I have no idea why it started doing.. Seems weird just because of the Root option change.

**Comment by Schaka** [comment]
I don't know what could've caused that but you have SO many addons that it's hard to tell what might interfere.
Go into WTF/AccountName/AccountName/SavedVariables and delete LoseControl.lua and LoseControl.lua.bak while your game is closed.
