### ISSUE TITLE
Icon location

### ISSUE THREAD

**Issue by OrangeCommodore** [Schaka/LoseControl#6]
Is it possible to move the icon location? By default it sits over top of my character, and I would like to move it.

**Comment by Schaka** [comment]
You can open the menu and move all icons...

**Comment by OrangeCommodore** [comment]
What is the command to open the menu?

**Comment by OrangeCommodore** [comment]
What is the command to open the menu? I do not see an icon to do so.

**Comment by Schaka** [comment]
/lc or /losecontrol
It says so in chat when you first log in and it's in the addons menu if you go to ESC -> Interface
